<?php

namespace App\Constants;

return [
    'DESIGNS_IMAGE_MAX_SIZE'=>'2048',
    'DESIGNS_IMAGE_MIN_SIZE'=>'10',
    
    'VISION_MISSION_IMAGE_MAX_SIZE'=>'2048',
    'VISION_MISSION_IMAGE_MIN_SIZE'=>'10',
    
    'PRODUCT_SERVICES_IMAGE_MAX_SIZE'=>'1048',
    'PRODUCT_SERVICES_IMAGE_MIN_SIZE'=>'10',
    
    'TESTIMONIAL_IMAGE_MAX_SIZE'=>'1048',
    'TESTIMONIAL_IMAGE_MIN_SIZE'=>'10',

    'PRODUCT_IMAGE_MAX_SIZE'=>'1048',
    'PRODUCT_IMAGE_MIN_SIZE'=>'10',

    'DIRECTOR_DESK_IMAGE_MAX_SIZE'=>'1048',
    'DIRECTOR_DESK_IMAGE_MIN_SIZE'=>'10',

    'SERVICES_IMAGE_MAX_SIZE'=>'1048',
    'SERVICES_IMAGE_MIN_SIZE'=>'10',

    'TEAM_IMAGE_MAX_SIZE'=>'1048',
    'TEAM_IMAGE_MIN_SIZE'=>'10',

    'NOTICE_IMAGE_MAX_SIZE'=>'1048',
    'NOTICE_IMAGE_MIN_SIZE'=>'10',
    
];