<?php

namespace App\Constants;

return [
'IMAGE_MIN_WIDTH'=>'200',
'IMAGE_MIN_HEIGHT'=>'200',
'IMAGE_MAX_WIDTH'=>'600',
'IMAGE_MAX_HEIGHT'=>'600',
    
    'DESIGNS_PDF_MAX_SIZE'=>'6144',
    'DESIGNS_PDF_MIN_SIZE'=>'1',

    'DESIGNS_IMAGE_MAX_SIZE'=>'5120',
    'DESIGNS_IMAGE_MIN_SIZE'=>'1',
    
    'VISION_MISSION_IMAGE_MAX_SIZE'=>'2048',
    'VISION_MISSION_IMAGE_MIN_SIZE'=>'1',
    
    'PRODUCT_SERVICES_IMAGE_MAX_SIZE'=>'1048',
    'PRODUCT_SERVICES_IMAGE_MIN_SIZE'=>'1',
    
    'TESTIMONIAL_IMAGE_MAX_SIZE'=>'1048',
    'TESTIMONIAL_IMAGE_MIN_SIZE'=>'1',

    'PRODUCT_IMAGE_MAX_SIZE'=>'1048',
    'PRODUCT_IMAGE_MIN_SIZE'=>'1',

    'DIRECTOR_DESK_IMAGE_MAX_SIZE'=>'1048',
    'DIRECTOR_DESK_IMAGE_MIN_SIZE'=>'1',

    'SERVICES_IMAGE_MAX_SIZE'=>'1048',
    'SERVICES_IMAGE_MIN_SIZE'=>'1',

    'TEAM_IMAGE_MAX_SIZE'=>'1048',
    'TEAM_IMAGE_MIN_SIZE'=>'1',

    'NOTICE_IMAGE_MAX_SIZE'=>'1048',
    'NOTICE_IMAGE_MIN_SIZE'=>'1',
    
];